version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: course-realworld-docker-frontend
    command: serve -s build -l 3000
    # because we use nginx
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
    networks:
      - course-realworld-docker-network

  api:
    build: ./api
    container_name: course-realworld-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      # - HOST=http://localhost
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - course-realworld-docker-network

  auth:
    build: ./auth
    container_name: course-realworld-docker-auth
    command: npm run start
    restart: unless-stopped
    # ports:
    #   - "3002:3002"
    environment:
      - PORT=3002
      # - HOST=http://localhost
      - MONGO_URL=mongodb://api_db:27017/api
      - API_URL=http://api:3001/api
    depends_on:
      - api_db
    networks:
      - course-realworld-docker-network

  api_db:
    image: mongo:latest
    container_name: course-realworld-docker-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - course-realworld-docker-network

  auth_db:
    image: mongo:latest
    container_name: course-realworld-docker-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - course-realworld-docker-network

  nginx:
    image: nginx:stable-alpine
    container_name: course-realworld-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - course-realworld-docker-network

volumes:
    mongodb_api:
    mongodb_auth:

networks:
  course-realworld-docker-network:
    driver: bridge